# Generated by Django 2.1.7 on 2019-04-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('continentName', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('countryID', 'continentName', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('merchantID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('merchantName', models.CharField(max_length=1000)),
                ('merchantCreatedAt', models.DateField()),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Countries')),
            ],
            options={
                'ordering': ('merchantID', 'merchantName', 'countryID', 'merchantCreatedAt', 'userID'),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('orderItemID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quantitity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('orderItemID', 'productID', 'quantitity'),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('orderCreatedAt', models.DateField()),
            ],
            options={
                'ordering': ('orderID', 'userID', 'status', 'orderCreatedAt'),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('productCreatedAt', models.DateField()),
                ('merchantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Merchants')),
            ],
            options={
                'ordering': ('productID', 'merchantID', 'price', 'price', 'productCreatedAt', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not specified', 'Not specified')], max_length=15)),
                ('birthDate', models.DateField()),
                ('userCreatedAt', models.DateField()),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Countries')),
            ],
            options={
                'ordering': ('userID', 'fullName', 'email', 'gender', 'birthDate', 'userCreatedAt', 'countryID'),
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Users'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Users'),
        ),
        migrations.AddField(
            model_name='merchants',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Users'),
        ),
    ]
