# Generated by Django 2.2.3 on 2019-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounds',
            name='provider',
            field=models.CharField(default='unkown', max_length=100),
        ),
    ]
