# Generated by Django 2.2 on 2019-04-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemo', '0002_auto_20190414_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecules',
            fields=[
                ('moleculeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('moleculeID', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('structureID', models.AutoField(primary_key=True, serialize=False)),
                ('smiles', models.CharField(max_length=5000)),
                ('inChi', models.CharField(max_length=5000)),
                ('inChiKey', models.CharField(max_length=14)),
                ('moleculeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Molecules')),
            ],
            options={
                'ordering': ('structureID', 'moleculeID', 'smiles', 'inChi', 'inChiKey'),
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('propertyID', models.AutoField(primary_key=True, serialize=False)),
                ('pka', models.FloatField()),
                ('charge', models.FloatField()),
                ('molarMass', models.FloatField()),
                ('monoIsotropicMass', models.FloatField()),
                ('clogp', models.FloatField()),
                ('tpsa', models.FloatField()),
                ('lipinski', models.SmallIntegerField()),
                ('hBond', models.SmallIntegerField()),
                ('hBondDonnors', models.SmallIntegerField()),
                ('rotatableBonds', models.SmallIntegerField()),
                ('moleculeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Molecules')),
            ],
            options={
                'ordering': ('propertyID', 'moleculeID', 'pka', 'charge', 'molarMass', 'monoIsotropicMass', 'clogp', 'tpsa', 'lipinski', 'hBond', 'hBondDonnors', 'rotatableBonds'),
            },
        ),
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('figureID', models.AutoField(primary_key=True, serialize=False)),
                ('molecule', models.CharField(max_length=5000)),
                ('surface', models.CharField(max_length=5000)),
                ('pka', models.FloatField()),
                ('moleculeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemo.Molecules')),
            ],
            options={
                'ordering': ('figureID', 'moleculeID', 'molecule', 'surface', 'pka'),
            },
        ),
    ]
